// <auto-generated />
namespace Hogon.Store.Models.FluentAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Brand_Area : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Brand_Area));
        
        string IMigrationMetadata.Id
        {
            get { return "201707310748208_Brand_Area"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
