// <auto-generated />
namespace Hogon.Store.Models.FluentAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateFreebie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateFreebie));
        
        string IMigrationMetadata.Id
        {
            get { return "201708080942459_updateFreebie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
